title: Streamdata Gallery AWS Marketplace Metering Service
url: aws-marketplace-metering-service.streamdata.gallery
tag: AWS Marketplace Metering Service
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: aws-marketplace-metering-service
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
